name: Build & deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          node-version: 16.15.1
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run test
        run: yarn test
#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<ssv-web (stage)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - name: Run stage ssv-web build
        if: github.ref == 'refs/heads/stage'
        run: >
          SSV_API_ENDPOINT="$SSV_API_ENDPOINT" CONTRACT_ADDRESS="$NETWORK_CONTRACT_ADDRESS" GOOGLE_TAG_SECRET="$GOOGLE_TAG_SECRET"
          EXPLORER_URL="$EXPLORER_URL" EXPLORER_VERSION="$EXPLORER_VERSION" EXPLORER_NETWORK="$EXPLORER_NETWORK" BLOCKNATIVE_KEY="$BLOCKNATIVE_KEY" yarn build
        env:
          BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
          EXPLORER_URL: "https://explorer.stage.ssv.network"
          EXPLORER_VERSION: "v2"
          EXPLORER_NETWORK: "prater"
          LINK_SSV_DEV_DOCS: ${{ secrets.LINK_SSV_DEV_DOCS }}
          BLOX_INFRA_API: 'https://api.stage.bloxstaking.com'
          GOOGLE_TAG_SECRET: ${{ secrets.STAGE_GOOGLE_TAG_SECRET }}
          SSV_API_ENDPOINT: ${{ secrets.STAGE_V2_API_ENDPOINT }}
          SSV_CONTRACT_ADDRESS: ${{ secrets.GOERLI_STAGE_SSV_CONTRACT_ADDRESS }}
          NETWORK_CONTRACT_ADDRESS: ${{ secrets.STAGE_V2_NETWORK_CONTRACT_ADDRESS }}
          DISTRIBUTION_CONTRACT_ADDRESS: ${{ secrets.STAGE_DISTRIBUTION_CONTRACT_ADDRESS }}

      - name: Deploy stage ssv-web
        if: github.ref == 'refs/heads/stage'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build/'
          AWS_REGION: 'us-west-2'
          AWS_S3_BUCKET: ${{ secrets.STAGE_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGE_AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}
#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<ssv-web (stage)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<ssv-web (stage V3)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - name: Run stage ssv-web build
        if: github.ref == 'refs/heads/stageV3'
        run: >
          SSV_API_ENDPOINT="$SSV_API_ENDPOINT" CONTRACT_ADDRESS="$NETWORK_SETTER_CONTRACT_ADDRESS" GOOGLE_TAG_SECRET="$GOOGLE_TAG_SECRET"
          EXPLORER_URL="$EXPLORER_URL" EXPLORER_VERSION="$EXPLORER_VERSION" EXPLORER_NETWORK="$EXPLORER_NETWORK" BLOCKNATIVE_KEY="$BLOCKNATIVE_KEY" yarn build
        env:
          BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
          EXPLORER_URL: "https://explorer.stage.ssv.network"
          EXPLORER_VERSION: "v3"
          EXPLORER_NETWORK: "prater"
          LINK_SSV_DEV_DOCS: ${{ secrets.LINK_SSV_DEV_DOCS }}
          BLOX_INFRA_API: 'https://api.stage.bloxstaking.com'
          GOOGLE_TAG_SECRET: ${{ secrets.STAGE_GOOGLE_TAG_SECRET }}
          SSV_API_ENDPOINT: ${{ secrets.STAGE_V3_API_ENDPOINT }}
          SSV_CONTRACT_ADDRESS: ${{ secrets.GOERLI_STAGE_SSV_CONTRACT_ADDRESS }}
          NETWORK_SETTER_CONTRACT_ADDRESS: ${{ secrets.NETWORK_SETTER_CONTRACT_ADDRESS }}
          NETWORK_GETTER_CONTRACT_ADDRESS: ${{ secrets.NETWORK_GETTER_CONTRACT_ADDRESS }}

      - name: Deploy stage ssv-web
        if: github.ref == 'refs/heads/stageV3'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build/'
          AWS_REGION: 'us-west-2'
          AWS_S3_BUCKET: ${{ secrets.STAGE_V3_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGE_AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}
#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<ssv-web (stage V3)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<ssv-web (prod V3)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - name: Run stage ssv-web build
        if: github.ref == 'refs/heads/mainV3'
        run: >
          SSV_API_ENDPOINT="$SSV_API_ENDPOINT" CONTRACT_ADDRESS="$NETWORK_SETTER_CONTRACT_ADDRESS" GOOGLE_TAG_SECRET="$GOOGLE_TAG_SECRET"
          EXPLORER_URL="$EXPLORER_URL" EXPLORER_VERSION="$EXPLORER_VERSION" EXPLORER_NETWORK="$EXPLORER_NETWORK" BLOCKNATIVE_KEY="$BLOCKNATIVE_KEY" yarn build
        env:
          EXPLORER_VERSION: "v3"
          EXPLORER_NETWORK: "prater"
          EXPLORER_URL: "https://explorer.ssv.network"
          BLOX_INFRA_API: 'https://api.bloxstaking.com'
          BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
          LINK_SSV_DEV_DOCS: ${{ secrets.LINK_SSV_DEV_DOCS }}
          SSV_API_ENDPOINT: ${{ secrets.PROD_V3_API_ENDPOINT }}
          GOOGLE_TAG_SECRET: ${{ secrets.STAGE_GOOGLE_TAG_SECRET }}
          SSV_CONTRACT_ADDRESS: ${{ secrets.GOERLI_PROD_SSV_CONTRACT_ADDRESS }}
          NETWORK_SETTER_CONTRACT_ADDRESS: ${{ secrets.NETWORK_SETTER_CONTRACT_ADDRESS }}
          NETWORK_GETTER_CONTRACT_ADDRESS: ${{ secrets.NETWORK_GETTER_CONTRACT_ADDRESS }}

      - name: Deploy stage ssv-web
        if: github.ref == 'refs/heads/mainV3'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build/'
          AWS_REGION: 'us-west-2'
          AWS_S3_BUCKET: ${{ secrets.PROD_V3_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<ssv-web (stage V3)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<faucet-web (stage)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - name: Run stage faucet build
        if: github.ref == 'refs/heads/stage'
        run: >
          SSV_API_ENDPOINT="$SSV_API_ENDPOINT" CONTRACT_ADDRESS="$NETWORK_CONTRACT_ADDRESS" GOOGLE_TAG_SECRET="$GOOGLE_TAG_SECRET"
          EXPLORER_URL="$EXPLORER_URL" EXPLORER_VERSION="$EXPLORER_VERSION" EXPLORER_NETWORK="$EXPLORER_NETWORK" BLOCKNATIVE_KEY="$BLOCKNATIVE_KEY" yarn build
        env:
          REACT_APP_FAUCET_PAGE: "true"
          BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
          EXPLORER_URL: "https://explorer.stage.ssv.network/"
          EXPLORER_VERSION: "v2"
          EXPLORER_NETWORK: "prater"
          LINK_SSV_DEV_DOCS: ${{ secrets.LINK_SSV_DEV_DOCS }}
          BLOX_INFRA_API: 'https://api.stage.bloxstaking.com'
          REACT_APP_CAPTCHA_KEY: ${{ secrets.CAPTCHA_KEY_STAGE }}
          SSV_API_ENDPOINT: ${{ secrets.STAGE_V2_API_ENDPOINT }}
          NETWORK_CONTRACT_ADDRESS: ${{ secrets.STAGE_CONTRACT_ADDRESS }}
          SSV_CONTRACT_ADDRESS: ${{ secrets.GOERLI_STAGE_SSV_CONTRACT_ADDRESS }}

      - name: Deploy stage faucet
        if: github.ref == 'refs/heads/stage'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build/'
          AWS_REGION: 'us-west-2'
          AWS_S3_BUCKET: ${{ secrets.STAGE_FAUCET_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGE_AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}
#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<faucet-web (stage)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<claim-web (stage)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - name: Run stage Claim build
        if: github.ref == 'refs/heads/stage'
        run: >
          SSV_API_ENDPOINT="$SSV_API_ENDPOINT" CONTRACT_ADDRESS="$NETWORK_CONTRACT_ADDRESS" GOOGLE_TAG_SECRET="$GOOGLE_TAG_SECRET"
          EXPLORER_URL="$EXPLORER_URL" BLOCKNATIVE_KEY="$BLOCKNATIVE_KEY" PROD_CLAIM_PAGE="$PROD_CLAIM_PAGE" yarn build
        env:
          PROD_CLAIM_PAGE: "true"
          BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
          EXPLORER_URL: "https://explorer.stage.ssv.network"
          BLOX_INFRA_API: 'https://api.stage.bloxstaking.com'
          LINK_SSV_DEV_DOCS: ${{ secrets.LINK_SSV_DEV_DOCS }}
          GOOGLE_TAG_SECRET: ${{ secrets.STAGE_GOOGLE_TAG_SECRET }}
          SSV_API_ENDPOINT: ${{ secrets.STAGE_V2_API_ENDPOINT }}
          NETWORK_CONTRACT_ADDRESS: ${{ secrets.STAGE_V2_NETWORK_CONTRACT_ADDRESS }}
          SSV_CONTRACT_ADDRESS: ${{ secrets.secrets.GOERLI_STAGE_SSV_CONTRACT_ADDRESS }}
          DISTRIBUTION_CONTRACT_ADDRESS: ${{ secrets.STAGE_DISTRIBUTION_CONTRACT_ADDRESS }}

      - name: Deploy claim stage
        if: github.ref == 'refs/heads/stage'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build/'
          AWS_REGION: 'us-west-2'
          AWS_S3_BUCKET: ${{ secrets.STAGE_V2_AWS_S3_BUCKET_CLAIM }}
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGE_AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}

      - name: Run prod build claim
        if: github.ref == 'refs/heads/main'
        run: >
          OPERATORS_ENDPOINT="$OPERATORS_ENDPOINT" CONTRACT_ADDRESS="$NETWORK_CONTRACT_ADDRESS" GOOGLE_TAG_SECRET="$GOOGLE_TAG_SECRET"
          EXPLORER_URL="$EXPLORER_URL" BLOCKNATIVE_KEY="$BLOCKNATIVE_KEY" PROD_CLAIM_PAGE="$PROD_CLAIM_PAGE" yarn build
        env:
          PROD_CLAIM_PAGE: "true"
          BLOX_INFRA_API: 'https://api.bloxstaking.com'
          BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
          EXPLORER_URL: "https://explorer.shifu.ssv.network"
          LINK_SSV_DEV_DOCS: ${{ secrets.LINK_SSV_DEV_DOCS }}
          GOOGLE_TAG_SECRET: ${{ secrets.PROD_GOOGLE_TAG_SECRET }}
          OPERATORS_ENDPOINT: ${{ secrets.PROD_OPERATORS_ENDPOINT }}
          SSV_CONTRACT_ADDRESS: ${{ secrets.GOERLI_PROD_SSV_CONTRACT_ADDRESS }}
          NETWORK_CONTRACT_ADDRESS: ${{ secrets.PROD_NETWORK_CONTRACT_ADDRESS }}
          DISTRIBUTION_CONTRACT_ADDRESS: ${{ secrets.PROD_DISTRIBUTION_CONTRACT_ADDRESS }}


      - name: Deploy prod claim
        if: github.ref == 'refs/heads/main'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build/'
          AWS_REGION: 'us-west-2'
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET_CLAIM }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<claim-web (prod)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<ssv-web (prod)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - name: Run prod ssv-web build
        if: github.ref == 'refs/heads/main'
        run: >
          OPERATORS_ENDPOINT="$OPERATORS_ENDPOINT" CONTRACT_ADDRESS="$NETWORK_CONTRACT_ADDRESS" GOOGLE_TAG_SECRET="$GOOGLE_TAG_SECRET"
          EXPLORER_URL="$EXPLORER_URL" BLOCKNATIVE_KEY="$BLOCKNATIVE_KEY" PROD_CLAIM_PAGE="$PROD_CLAIM_PAGE" yarn build
        env:
          PROD_CLAIM_PAGE: ""
          BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
          EXPLORER_URL: "https://explorer.ssv.network"
          LINK_SSV_DEV_DOCS: ${{ secrets.LINK_SSV_DEV_DOCS }}
          BLOX_INFRA_API: 'https://api.bloxstaking.com'
          GOOGLE_TAG_SECRET: ${{ secrets.PROD_GOOGLE_TAG_SECRET }}
          OPERATORS_ENDPOINT: ${{ secrets.PROD_OPERATORS_ENDPOINT_v2 }}
          SSV_CONTRACT_ADDRESS: ${{ secrets.GOERLI_PROD_SSV_CONTRACT_ADDRESS }}
          NETWORK_CONTRACT_ADDRESS: ${{ secrets.PROD_NETWORK_CONTRACT_ADDRESS_V2 }}
          DISTRIBUTION_CONTRACT_ADDRESS: ${{ secrets.PROD_DISTRIBUTION_CONTRACT_ADDRESS }}


      - name: Deploy prod ssv-web
        if: github.ref == 'refs/heads/main'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build/'
          AWS_REGION: 'us-west-2'
          AWS_S3_BUCKET: ${{ secrets.PROD_V2_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<ssv-web (prod) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<faucet-web (prod)>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - name: Run prod faucet build
        if: github.ref == 'refs/heads/main'
        run: >
          OPERATORS_ENDPOINT="$OPERATORS_ENDPOINT" CONTRACT_ADDRESS="$NETWORK_CONTRACT_ADDRESS" GOOGLE_TAG_SECRET="$GOOGLE_TAG_SECRET"
          EXPLORER_URL="$EXPLORER_URL" BLOCKNATIVE_KEY="$BLOCKNATIVE_KEY" yarn build
        env:
          REACT_APP_FAUCET_PAGE: "true"
          BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
          EXPLORER_URL: "https://explorer.ssv.network/"
          LINK_SSV_DEV_DOCS: ${{ secrets.LINK_SSV_DEV_DOCS }}
          REACT_APP_CAPTCHA_KEY: ${{ secrets.CAPTCHA_KEY_STAGE }}
          OPERATORS_ENDPOINT: ${{ secrets.PROD_OPERATORS_ENDPOINT_v2 }}
          NETWORK_CONTRACT_ADDRESS: ${{ secrets.STAGE_CONTRACT_ADDRESS }}
          SSV_CONTRACT_ADDRESS: ${{ secrets.GOERLI_PROD_SSV_CONTRACT_ADDRESS }}

      - name: Deploy prod faucet
        if: github.ref == 'refs/heads/main'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build/'
          AWS_REGION: 'us-west-2'
          AWS_S3_BUCKET: ${{ secrets.PROD_FAUCET_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
